SELECT DISTINCT FD.HANDLE || '-' || CC.HANDLE AS ID,
                ESTADOS.NOME ESTADO,
                EMP.NOME AS EMPRESA,
                FI.NOME AS FILIAIS,
                CC.K_DIVISAODRE AS DIVISAO_DRE,
                CC.ESTRUTURA AS CODIGO_CC,
                GP.CODIGO,
                GP.K_MONITOR AS CODIGO_MONITOR,
                GP.NOME CLIENTE,
                CC.NOME CENTRO_CUSTO,
                CTC.NOME AS RECEITA_MASTER,
                FC.ESTRUTURA,
                FD.NUMEROPEDIDO CONTRATO,
                CAST(C.OBJETOCONTRATO AS VARCHAR(600)) AS OBJETOCONTRATO,
                FD.HANDLE DOCUMENTO,
                FD.DOCUMENTOCONTABIL AS DOCUMENTO_CONTABIL,
                P.NOME ITEM,
                P.HANDLE,
                CI.HANDLE AS HANDLE_ITEM,
                CI.VALORTOTAL VALOR_TOTAL,
                CASE
                    WHEN INSTR(P.NOME, '(ISS RETIDO)', -1) > 0 THEN CI.VALORTOTAL - (CI.IRFVALOR + CI.VALORINSS + CI.VALORPISRETIDO + CI.VALORCSLL + CI.VALORCOFINSRETIDO + CI.VALORIRPJ + CI.ISSVALOR)
                    ELSE CI.VALORTOTAL - (CI.IRFVALOR + CI.VALORINSS + CI.VALORPISRETIDO + CI.VALORCSLL + CI.VALORCOFINSRETIDO + CI.VALORIRPJ)
                END AS VALORLIQUIDO,
                CI.ISSVALOR AS ISS,
                ((CASE
                      WHEN INSTR(P.NOME, '(ISS RETIDO)', -1) >0 THEN CI.VALORTOTAL - (CI.IRFVALOR + CI.VALORINSS + CI.VALORPISRETIDO + CI.VALORCSLL + CI.VALORCOFINSRETIDO + CI.VALORIRPJ + CI.ISSVALOR)
                      ELSE CI.VALORTOTAL - (CI.IRFVALOR + CI.VALORINSS + CI.VALORPISRETIDO + CI.VALORCSLL + CI.VALORCOFINSRETIDO + CI.VALORIRPJ)
                  END) - CI.ISSVALOR) AS BASE_VALOR_PROVISAO,
                GP.APELIDO,
                TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS') AS DATAATUALIZACAO,
                DECODE(GP.EHORGAOPUBLICO, 'S', 'PÚBLICO', 'N', 'PRIVADO') TIPO,
                OPOR.OPORTUNIDADE_ITEM AS NOME_CODIGO,
                C.HANDLE AS HANDLE_CONTRATO
FROM BENNERCORP.FN_LANCAMENTOS FL
LEFT OUTER JOIN BENNERCORP.FN_LANCAMENTOCC LC ON (LC.LANCAMENTO = FL.HANDLE)
LEFT JOIN BENNERCORP.FN_CONTAS FC ON (FC.HANDLE = FL.CONTA)
LEFT JOIN BENNERCORP.FN_DOCUMENTOS FD ON (FD.HANDLE = FL.DOCUMENTO)
LEFT JOIN BENNERCORP.GN_PESSOAS GP ON (GP.HANDLE = FD.PESSOA)
LEFT JOIN BENNERCORP.ESTADOS ON (ESTADOS.HANDLE = GP.ESTADO)
LEFT JOIN BENNERCORP.CN_CONTRATOS C ON (C.NUMERO = FD.NUMEROPEDIDO)
LEFT JOIN BENNERCORP.CN_CONTRATOS C2 ON (C.NUMERO = FD.NUMEROPEDIDO
                                         AND FD.TIPODEMOVIMENTO = 1)--XXX
LEFT JOIN BENNERCORP.CT_CC CC ON (CC.HANDLE = LC.CENTROCUSTO)
LEFT JOIN BENNERCORP.CM_ITENS CI ON (CI.DOCUMENTO = FD.HANDLE)
LEFT JOIN BENNERCORP.FILIAIS FI ON (FL.FILIAL = FI.HANDLE)
LEFT JOIN BENNERCORP.EMPRESAS EMP ON (FL.EMPRESA = EMP.HANDLE)
LEFT JOIN BENNERCORP.PD_PRODUTOS P ON (P.HANDLE = CI.PRODUTO)
INNER JOIN BENNERCORP.PD_PRODUTOSPAI PAI ON (P.PRODUTOPAI = PAI.HANDLE)
LEFT JOIN BENNERCORP.CT_CONTAS CTC ON (PAI.CONTACONTABILVENDA = CTC.HANDLE)
LEFT JOIN BENNERCORP.GN_OPERACOES OP ON (OP.HANDLE = FD.OPERACAO)
LEFT JOIN BENNERCORP.FN_TIPOSDOCUMENTOS TD ON (TD.HANDLE = FD.TIPODOCUMENTO)
LEFT JOIN
  (SELECT CO.CONTRATO,
          CO.PRODUTO,
          LISTAGG(CO.NOMECODIGO, '; ') WITHIN GROUP (
                                                     ORDER BY CO.CONTRATO,
                                                              CO.PRODUTO) AS OPORTUNIDADE_ITEM
   FROM
     (SELECT DISTINCT CO.CONTRATO,
                      CO.PRODUTO,
                      OPOR.NOMECODIGO
      FROM BENNERCORP.CN_CONTRATOOBJETOS CO
      INNER JOIN BENNERCORP.K_CODIGOOPORTUNIDADE OPOR ON (CO.K_CODIGOOPORTUNIDADE = OPOR.HANDLE)) CO
   GROUP BY CO.CONTRATO,
            CO.PRODUTO) OPOR ON (OPOR.CONTRATO = C.HANDLE
                                 AND OPOR.PRODUTO = P.HANDLE)
WHERE GP.EHCLIENTE = 'S'
  AND CI.CENTROCUSTO = CC.HANDLE
  AND CI.CONTAFINANCEIRA = FC.HANDLE
  AND FD.NUMEROPEDIDO = 'FQF/00024179/2024'
  --AND FD.DATAEMISSAO BETWEEN TO_DATE('01/01/2020', 'DD/MM/YYYY') AND  TO_DATE('30/12/2020', 'DD/MM/YYYY')
  AND GP.CODIGO NOT IN (873163)
  AND FD.TIPODOCUMENTO NOT IN (57)
  AND FD.DATACANCELAMENTO IS NULL
  AND FD.NRNOTAFISCAL IS NOT NULL
  AND DECODE(FC.ESTRUTURA, '1.03.21', 'A', '1.06.01', 'A', '1.11.06', 'A', '1.11.09', 'A', '1.11.18', 'A', '1.19.04', 'A', '2.02.20', 'A', '2.02.23', 'A', '2.02.30', 'A', '2.02.35', 'A', '2.02.45', 'A', '2.03.31', 'A', '2.04.11', 'A', '2.04.13', 'A', '2.04.30', 'A', '2.06.02', 'A', '2.06.05', 'A', '2.06.14', 'A', '2.06.16', 'A', '2.06.45', 'A', '2.06.51', 'A', '2.07.02', 'A', '2.07.07', 'A', '2.07.12', 'A', '2.08.12', 'A', '2.08.13', 'A', '2.08.14', 'A', '2.08.15', 'A', '2.08.16', 'A', '2.08.17', 'A', '2.09.04', 'A', '2.09.05', 'A', '2.09.13', 'A', '2.09.20', 'A') IS NULL
  ORDER BY FD.HANDLE