select provisionamentos.id 
        ,provisionamentos.estado
        ,provisionamentos.empresa
        ,provisionamentos.filiais
        ,provisionamentos.divisao_dre
        ,provisionamentos.codigo_cc
        ,provisionamentos.codigo
        ,provisionamentos.codigo_monitor
        ,provisionamentos.cliente
        ,provisionamentos.centro_custo
        ,provisionamentos.receita_master
        ,provisionamentos.estrutura
        ,provisionamentos.contrato
        ,provisionamentos.objetocontrato
        ,provisionamentos.documento
        ,provisionamentos.documento_contabil
        ,provisionamentos.item
        ,provisionamentos.handle
        ,provisionamentos.handle_item
        ,provisionamentos.valor_total
        ,provisionamentos.valorliquido
        ,provisionamentos.iss
        ,provisionamentos.base_valor_provisao
        ,provisionamentos.apelido
        ,provisionamentos.dataatualizacao
        ,provisionamentos.tipo
        ,provisionamentos.nome_codigo
        ,provisionamentos.handle_contrato
        ,recebimentos.documento_id
        ,recebimentos.doc_origem_id
        ,recebimentos.documentonf
        ,recebimentos.doc_numero_pedido
        ,recebimentos.oportunidade
        ,recebimentos.filial_id
        ,recebimentos.filial
        ,recebimentos.numero_nota
        ,recebimentos.emissao
        ,recebimentos.datacancelamento
        ,recebimentos.datavencimento
        ,recebimentos.datainclusao
        ,recebimentos.dataliquidacao
        ,recebimentos.data_da_baixa
        ,recebimentos.codigo_cliente_portal_fin
        ,recebimentos.codigo_cliente
        ,recebimentos.nome_cliente
        ,recebimentos.parcela_id
        ,recebimentos.valor_faturado_bruto
        ,recebimentos.valor_faturado_liquido
        ,recebimentos.fator_do_item
        ,recebimentos.valor_faturado_liquido_s_iss
        ,recebimentos.valor_do_item
        ,recebimentos.valor_parcela
        ,recebimentos.valor_a_rec_por_item
        ,recebimentos.aliquota_iss
        ,recebimentos.valor_iss_da_parcela
        ,recebimentos.valor_a_rec_por_item_s_iss
        ,recebimentos.vl_recebido_bruto
        ,recebimentos.vl_recebido_liquido
        ,recebimentos.valor_recebido_por_item
        ,recebimentos.valor_recebido_por_item_bruto
        ,recebimentos.vl_juros_recebido
        ,recebimentos.valor_rec_por_item_bruto_c_j
        ,recebimentos.valor_base_comissao 
from provisionamentos 
left join recebimentos  on recebimentos.doc_origem_id = provisionamentos.documento and
                            recebimentos.handle_item = painel.handle_item 